option = {
    title: {
        text: "github/tags/graph-visualization 可视化",
        link: 'https://github.com/topics/graph-visualization'
    },
    tooltip: {},
    series: [{
        type: 'wordCloud',
        gridSize: 20,
        sizeRange: [12, 50],
        rotationRange: [0, 0],
        shape: 'circle',
        textStyle: {
            normal: {
                color: function() {
                    return 'rgb(' + [
                        Math.round(Math.random() * 160),
                        Math.round(Math.random() * 160),
                        Math.round(Math.random() * 160)
                    ].join(',') + ')';
                }
            },
            emphasis: {
                shadowBlur: 10,
                shadowColor: '#333'
            }
        },
        data: [{
            "name": "networkx",
            "value": 4000
        }, {
            "name": "grakn",
            "value": 918
        }, {
            "name": "ggraph",
            "value": 704
        }, {
            "name": "ggraph",
            "value": 521
        }, {
            "name": "neo4jd3",
            "value": 181
        }, {
            "name": "jira-dependency-graph",
            "value": 60
        }, {
            "name": "pyNMS",
            "value": 51
        }, {
            "name": "ImsvGraphVis",
            "value": 45
        }, {
            "name": "GraphPlot.jl",
            "value": 44
        }, {
            "name": "dc.graph.js",
            "value": 36
        }, {
            "name": "neo4j-3d-force-graph",
            "value": 24
        }, {
            "name": "NetworkLayout.jl",
            "value": 18
        }, {
            "name": "grave",
            "value": 17
        }, {
            "name": "grasp",
            "value": 14
        }, {
            "name": "noflo-graphviz",
            "value": 13
        }, {
            "name": "visualize",
            "value": 12
        }, {
            "name": "multigraph",
            "value": 8
        }, {
            "name": "gradoop_demo",
            "value": 7
        }, {
            "name": "GSoC-Rogas",
            "value": 4
        }, {
            "name": "latticegraph_designer",
            "value": 3
        }, {
            "name": "csgraph_editor",
            "value": 3
        }, {
            "name": "Reddit-Karma-Prediction",
            "value": 2
        }, {
            "name": "awesome-design-science",
            "value": 2
        }, {
            "name": "GraphterEffects",
            "value": 2
        }, {
            "name": "graph-traversing-visualization",
            "value": 2
        }, {
            "name": "D3GraphPlot.jl",
            "value": 2
        }, {
            "name": "atlas-algorithm",
            "value": 2
        }, {
            "name": "gvf_afel",
            "value": 1
        }, {
            "name": "ansible-role-graphviz",
            "value": 1
        }, {
            "name": "GraphVisualizer",
            "value": 1
        }, {
            "name": "visualNetx",
            "value": 1
        }, {
            "name": "meshUp",
            "value": 1
        }, {
            "name": "netxanal",
            "value": 1
        }, {
            "name": "ipython-d3networkx",
            "value": 1
        }, {
            "name": "Easy-Digraph-Draw",
            "value": 1
        }, {
            "name": "graph_visualizer",
            "value": 1
        }, {
            "name": "ITCC.NetworkView",
            "value": 1
        }, {
            "name": "atlas",
            "value": 1
        }, {
            "name": "JSNetworkX",
            "value": 1
        }, {
            "name": "movie-stats-web",
            "value": 0
        }, {
            "name": "graph_visualization_Yelp",
            "value": 0
        }, {
            "name": "gensvg",
            "value": 0
        }, {
            "name": "tema",
            "value": 0
        }, {
            "name": "evograph",
            "value": 0
        }, {
            "name": "gvf_core",
            "value": 0
        }, {
            "name": "PyDot-Examples",
            "value": 0
        }, {
            "name": "EPredictor",
            "value": 0
        }, {
            "name": "PageRank",
            "value": 0
        }, {
            "name": "cytoscape.js-simulated-annealing",
            "value": 0
        }, {
            "name": "StickyGraph",
            "value": 0
        }, {
            "name": "strengths-finders",
            "value": 0
        }, {
            "name": "grakn",
            "value": 0
        }, {
            "name": "GraphterEffectsTool",
            "value": 0
        }, {
            "name": "kbn_network",
            "value": 0
        }, {
            "name": "nodesoup",
            "value": 0
        }, {
            "name": "ccw",
            "value": 0
        }, {
            "name": "graphcx",
            "value": 0
        }, {
            "name": "TSP",
            "value": 0
        }, {
            "name": "semaphore",
            "value": 0
        }, {
            "name": "graph-navigator",
            "value": 0
        }]
    }]
};
